name: npm

on:
  push:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Check if NPM_TOKEN is set
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN is not set, skipping job."
            exit 1
          fi
      - uses: actions/checkout@v4.2.2
      - name: Setup Volta
        uses: volta-cli/action@v4.2.1
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
